const awardsObj = {
  Pet: {
    HoneyBee: "🐝",
    PotbellyPig: "🐷",
    Dog: "🐶",
    Puppy: "🐕",
    securityK9: "🐕‍🦺",
    ProffesionalK9: "🦮",
    Poodle: "🐩",
    Wolf: "🐺",
    Fox: "🦊",
    Pony: "🐴",
    ShoebillStork: "🦤",
    Owl: "🦉",
    Parrot: "🦜",
    Eagle: "🦅",
    Sparrow: "🐦",
    Raccoon: "🦝",
    Sloth: "🦥",
    Bunny: "🐰",
    Hedgehog: "🦔",
    Beaver: "🦫",
    Otter: "🦦",
    Skunk: "🦨",
    Goose: "🪿",
    Badger: "🦡",
    Chipmunk: "🐿️",
    Koala: "🐨",
    SpiderMonkey: "🐒",
    BombayCat: "🐈‍⬛",
    TabbyCat: "🐈",
    PersianCat: "🐱",
    GuineaPig: "🐹",
    Snake: "🐍",
    AfricanPygmyMouse: "🐭",
    Penguin: "🐧",
    Turtle: "🐢",
    HermitCrab: "🐚",
    Rooster: "🐓",
    Hen: "🐔",
    Turkey: "🦃",
    Peacock: "🦚",
    Flamingo: "🦩",
    MallardDuck: "🦆",
    Swan: "🦢",
    Dove: "🕊️",
    BullFrog: "🐸",
    iguana: "🦎",
    Rabbit: "🐇",
  },
  Aquatic_Zoo_Pet: {
    seal: "🦭",
    shark: "🦈",
    dolphin: "🐬",
    spermWhale: "🐳",
    blueWhale: "🐋",
    giantOctopus: "🐙",
    giantSquid: "🦑",
  },
  Land_Zoo_Pet: {
    bear: "🐻",
    polarbear: "🐻‍❄️",
    pandabear: "🐼",
    kangaroo: "🦘",
    crocodile: "🐊",
    gorilla: "🦍",
    orangutan: "🦧",
    monkey: "🐵",
    lion: "🦁",
    tiger: "🐅",
    siberianTiger: "🐯",
    leopard: "🐆",
    elephant: "🐘",
    rhinoceros: "🦏",
    hippopotamus: "🦛",
    giraffe: "🦒",
    mammoth: "🦣",
  },
  Food_Cattle: {
    ox: "🐂",
    waterBuffalo: "🐃",
    cowMeat: "🐄",
    cowMilk: "🐮",
    buffalo: "🦬",
    ram: "🐏",
    ewe: "🐑",
    goat: "🐐",
    deer: "🦌",
  },
  Niche_Food_Creature: {
    Hog: "🐖",
    Boar: "🐗",
    PotbellyPig: "🐷",
    MeatRabbit: "🐇",
    HoneyBee: "🐝",
  },
  Baby_Bird: {
    UnbornChick: "🥚",
    HatchingChick: "🐣",
    BabyChick: "🐥",
    BabyBird: "🐤",
  },
  Poultry_Food_Creature: {
    rooster: "🐓",
    hen: "🐔",
    turkey: "🦃",
    peacock: "🦚",
    flamingo: "🦩",
    duck: "🦆",
    swan: "🦢",
    dove: "🕊️",
    goose: "🪿",
  },
  Aquatic_Creature_Food: {
    Shrimp: "🦐",
    Oyster: "🦪",
    Crab: "🦀",
    Octopus: "🐙",
    Fish: "🎣",
    Lobster: "🦞",
    Fugu: "🐡",
    LargeFish: "🐟",
    Prawns: "🍤",
    ExoticFish: "🐠",
    Squid: "🦑",
  },
  Utility_Creature_Cattle: {
    Camel: "🐪",
    BactrianCamel: "🐫",
    AmericanMustangHorse: "🐎",
    Zebra: "🦓",
    Llama: "🦙",
    Giraffe: "🦒",
  },
  Creeping_Thing: {
    ant: "🐜",
    ladybug: "🐞",
    snail: "🐌",
    butterfly: "🦋",
    caterpillar: "🐛",
    beetle: "🪲",
    grasshopper: "🦗",
    roach: "🪳",
    spider: "🕷️",
    scorpion: "🦂",
    mosquito: "🦟",
    fly: "🪰",
    worm: "🪱",
    bat: "🦇",
    mouse: "🐁",
    rat: "🐀",
  },
  Flower: {
    WildFlower: "🌼",
    SunFlower: "🌻",
    Hibiscus: "🌺",
    Rose: "🌹",
    CherryBlossom: "🌸",
    Tulip: "🌷",
    Rossete: "🏵️",
    Bouquet: "💐",
  },
  Tree: {
    EvergreenTree: "🌲",
    Cactus: "🌵",
    PalmTree: "🌴",
    DeciduousTree: "🌳",
    Seedling: "🌱",
    Sapling: "🌿",
    Bamboo: "🎍",
    BonsaiTree: "🪴",
  },
  Land: {
    VolcanoMountain: "🌋",
    SnowMountain: "🏔️",
    PristineDesert: "🏜️",
    GreenMountain: "⛰️",
    Island: "🏝️",
    LushMountain: "🏞️",
    MountFuji: "🗻",
  },
  Prepared_Food: {
    ButteredCroissant: "🥐",
    FreshPretzel: "🥨",
    CreamCheeseBagels: "🥯",
    Pancakes: "🥞",
    Waffles: "🧇",
    FriedCheese: "🧀",
    BBQribs: "🍖",
    FriedChicken: "🍗",
    CurryRice: "🍛",
    RamenNoodles: "🍜",
    Spaggetti: "🍝",
    FrenchFries: "🍟",
    Dango: "🍡",
    Sushi: "🍣",
    FriedShrimp: "🍤",
    FishCake: "🍥",
    IceCream: "🍦",
    ShavedIce: "🍧",
    IceCreamSundae: "🍨",
    Doughnuts: "🍩",
    Cookies: "🍪",
    Chocolate: "🍫",
    LoafBread: "🍞",
    RawSweetMilk: "🥛",
    Custard: "🍮",
    HoneyComb: "🍯",
    Cheesecake: "🍰",
    Cupcake: "🧁",
    BirthdayCake: "🎂",
    BentoBox: "🍱",
    Stew: "🍲",
    FriedEggs: "🍳",
    Hamburger: "🍔",
    Pizza: "🍕",
    RiceCracker: "🍘",
    SweetRiceBall: "🍙",
    Steak: "🥩",
    Bacon: "🥓",
    Sandwich: "🥪",
    Gyro: "🥙",
    Chilli: "🥫",
    ChowMein: "🥡",
    Falafel: "🧆",
    MilkShake: "🥤",
    Hotdogs: "🌭",
    Tacos: "🌮",
    Burrito: "🌯",
    Tamales: "🫔",
    Stirfry: "🥘",
    Fondue: "🫕",
    Cereal: "🥣",
    ChefSalad: "🥗",
    ButterPopcorn: "🍿",
    Dumpling: "🥟",
    FreshPie: "🥧",
    SweetBubbleTea: "🧋",
    FrenchBread: "🥖",
    friedBread: "🫓",
    grilledKabob: "🍢",
  },
  Fruit: {
    pear: "🍐",
    redApple: "🍎",
    mango: "🥭",
    melon: "🍈",
    cherry: "🍒",
    orange: "🍊",
    peach: "🍑",
    grapes: "🍇",
    pineapple: "🍍",
    blueberries: "🫐",
    coconut: "🥥",
    strawberry: "🍓",
    lemon: "🍋",
    greenApple: "🍏",
    kiwi: "🥝",
    bannana: "🍌",
    watermelon: "🍉",
    tomato: "🍅",
    avocado: "🥑",
  },
  Vegatable: {
    Avocado: "🥑",
    Eggplant: "🍆",
    Potato: "🥔",
    Carrot: "🥕",
    CornCobbed: "🌽",
    Peppers: "🌶️",
    BellPepper: "🫑",
    Cucumber: "🥒",
    Lettuce: "🥬",
    Broccoli: "🥦",
    GarlicClove: "🧄",
    Onion: "🧅",
    Mushroom: "🍄",
    Peanuts: "🥜",
    Chestnuts: "🌰",
    SweetPotato: "🍠",
    SpanishOlives: "🫒",
    BambooHeart: "🎍",
  },
  Cereal_Grain: {
    Rice: "🍚",
    Corn: "🌽",
    Wheat: "🌾",
  },
};
const chapterArray = [
  "Genesis>1",
  "Genesis>2",
  "Genesis>3",
  "Genesis>4",
  "Genesis>5",
  "Genesis>6",
  "Genesis>7",
  "Genesis>8",
  "Genesis>9",
  "Genesis>10",
  "Genesis>11",
  "Genesis>12",
  "Genesis>13",
  "Genesis>14",
  "Genesis>15",
  "Genesis>16",
  "Genesis>17",
  "Genesis>18",
  "Genesis>19",
  "Genesis>20",
  "Genesis>21",
  "Genesis>22",
  "Genesis>23",
  "Genesis>24",
  "Genesis>25",
  "Genesis>26",
  "Genesis>27",
  "Genesis>28",
  "Genesis>29",
  "Genesis>30",
  "Genesis>31",
  "Genesis>32",
  "Genesis>33",
  "Genesis>34",
  "Genesis>35",
  "Genesis>36",
  "Genesis>37",
  "Genesis>38",
  "Genesis>39",
  "Genesis>40",
  "Genesis>41",
  "Genesis>42",
  "Genesis>43",
  "Genesis>44",
  "Genesis>45",
  "Genesis>46",
  "Genesis>47",
  "Genesis>48",
  "Genesis>49",
  "Genesis>50",
  "Exodus>1",
  "Exodus>2",
  "Exodus>3",
  "Exodus>4",
  "Exodus>5",
  "Exodus>6",
  "Exodus>7",
  "Exodus>8",
  "Exodus>9",
  "Exodus>10",
  "Exodus>11",
  "Exodus>12",
  "Exodus>13",
  "Exodus>14",
  "Exodus>15",
  "Exodus>16",
  "Exodus>17",
  "Exodus>18",
  "Exodus>19",
  "Exodus>20",
  "Exodus>21",
  "Exodus>22",
  "Exodus>23",
  "Exodus>24",
  "Exodus>25",
  "Exodus>26",
  "Exodus>27",
  "Exodus>28",
  "Exodus>29",
  "Exodus>30",
  "Exodus>31",
  "Exodus>32",
  "Exodus>33",
  "Exodus>34",
  "Exodus>35",
  "Exodus>36",
  "Exodus>37",
  "Exodus>38",
  "Exodus>39",
  "Exodus>40",
  "Leviticus>1",
  "Leviticus>2",
  "Leviticus>3",
  "Leviticus>4",
  "Leviticus>5",
  "Leviticus>6",
  "Leviticus>7",
  "Leviticus>8",
  "Leviticus>9",
  "Leviticus>10",
  "Leviticus>11",
  "Leviticus>12",
  "Leviticus>13",
  "Leviticus>14",
  "Leviticus>15",
  "Leviticus>16",
  "Leviticus>17",
  "Leviticus>18",
  "Leviticus>19",
  "Leviticus>20",
  "Leviticus>21",
  "Leviticus>22",
  "Leviticus>23",
  "Leviticus>24",
  "Leviticus>25",
  "Leviticus>26",
  "Leviticus>27",
  "Numbers>1",
  "Numbers>2",
  "Numbers>3",
  "Numbers>4",
  "Numbers>5",
  "Numbers>6",
  "Numbers>7",
  "Numbers>8",
  "Numbers>9",
  "Numbers>10",
  "Numbers>11",
  "Numbers>12",
  "Numbers>13",
  "Numbers>14",
  "Numbers>15",
  "Numbers>16",
  "Numbers>17",
  "Numbers>18",
  "Numbers>19",
  "Numbers>20",
  "Numbers>21",
  "Numbers>22",
  "Numbers>23",
  "Numbers>24",
  "Numbers>25",
  "Numbers>26",
  "Numbers>27",
  "Numbers>28",
  "Numbers>29",
  "Numbers>30",
  "Numbers>31",
  "Numbers>32",
  "Numbers>33",
  "Numbers>34",
  "Numbers>35",
  "Numbers>36",
  "Deuteronomy>1",
  "Deuteronomy>2",
  "Deuteronomy>3",
  "Deuteronomy>4",
  "Deuteronomy>5",
  "Deuteronomy>6",
  "Deuteronomy>7",
  "Deuteronomy>8",
  "Deuteronomy>9",
  "Deuteronomy>10",
  "Deuteronomy>11",
  "Deuteronomy>12",
  "Deuteronomy>13",
  "Deuteronomy>14",
  "Deuteronomy>15",
  "Deuteronomy>16",
  "Deuteronomy>17",
  "Deuteronomy>18",
  "Deuteronomy>19",
  "Deuteronomy>20",
  "Deuteronomy>21",
  "Deuteronomy>22",
  "Deuteronomy>23",
  "Deuteronomy>24",
  "Deuteronomy>25",
  "Deuteronomy>26",
  "Deuteronomy>27",
  "Deuteronomy>28",
  "Deuteronomy>29",
  "Deuteronomy>30",
  "Deuteronomy>31",
  "Deuteronomy>32",
  "Deuteronomy>33",
  "Deuteronomy>34",
  "Joshua>1",
  "Joshua>2",
  "Joshua>3",
  "Joshua>4",
  "Joshua>5",
  "Joshua>6",
  "Joshua>7",
  "Joshua>8",
  "Joshua>9",
  "Joshua>10",
  "Joshua>11",
  "Joshua>12",
  "Joshua>13",
  "Joshua>14",
  "Joshua>15",
  "Joshua>16",
  "Joshua>17",
  "Joshua>18",
  "Joshua>19",
  "Joshua>20",
  "Joshua>21",
  "Joshua>22",
  "Joshua>23",
  "Joshua>24",
  "Judges>1",
  "Judges>2",
  "Judges>3",
  "Judges>4",
  "Judges>5",
  "Judges>6",
  "Judges>7",
  "Judges>8",
  "Judges>9",
  "Judges>10",
  "Judges>11",
  "Judges>12",
  "Judges>13",
  "Judges>14",
  "Judges>15",
  "Judges>16",
  "Judges>17",
  "Judges>18",
  "Judges>19",
  "Judges>20",
  "Judges>21",
  "Ruth>1",
  "Ruth>2",
  "Ruth>3",
  "Ruth>4",
  "Samuel1>1",
  "Samuel1>2",
  "Samuel1>3",
  "Samuel1>4",
  "Samuel1>5",
  "Samuel1>6",
  "Samuel1>7",
  "Samuel1>8",
  "Samuel1>9",
  "Samuel1>10",
  "Samuel1>11",
  "Samuel1>12",
  "Samuel1>13",
  "Samuel1>14",
  "Samuel1>15",
  "Samuel1>16",
  "Samuel1>17",
  "Samuel1>18",
  "Samuel1>19",
  "Samuel1>20",
  "Samuel1>21",
  "Samuel1>22",
  "Samuel1>23",
  "Samuel1>24",
  "Samuel1>25",
  "Samuel1>26",
  "Samuel1>27",
  "Samuel1>28",
  "Samuel1>29",
  "Samuel1>30",
  "Samuel1>31",
  "Samuel2>1",
  "Samuel2>2",
  "Samuel2>3",
  "Samuel2>4",
  "Samuel2>5",
  "Samuel2>6",
  "Samuel2>7",
  "Samuel2>8",
  "Samuel2>9",
  "Samuel2>10",
  "Samuel2>11",
  "Samuel2>12",
  "Samuel2>13",
  "Samuel2>14",
  "Samuel2>15",
  "Samuel2>16",
  "Samuel2>17",
  "Samuel2>18",
  "Samuel2>19",
  "Samuel2>20",
  "Samuel2>21",
  "Samuel2>22",
  "Samuel2>23",
  "Samuel2>24",
  "Kings1>1",
  "Kings1>2",
  "Kings1>3",
  "Kings1>4",
  "Kings1>5",
  "Kings1>6",
  "Kings1>7",
  "Kings1>8",
  "Kings1>9",
  "Kings1>10",
  "Kings1>11",
  "Kings1>12",
  "Kings1>13",
  "Kings1>14",
  "Kings1>15",
  "Kings1>16",
  "Kings1>17",
  "Kings1>18",
  "Kings1>19",
  "Kings1>20",
  "Kings1>21",
  "Kings1>22",
  "Kings2>1",
  "Kings2>2",
  "Kings2>3",
  "Kings2>4",
  "Kings2>5",
  "Kings2>6",
  "Kings2>7",
  "Kings2>8",
  "Kings2>9",
  "Kings2>10",
  "Kings2>11",
  "Kings2>12",
  "Kings2>13",
  "Kings2>14",
  "Kings2>15",
  "Kings2>16",
  "Kings2>17",
  "Kings2>18",
  "Kings2>19",
  "Kings2>20",
  "Kings2>21",
  "Kings2>22",
  "Kings2>23",
  "Kings2>24",
  "Kings2>25",
  "Chronicles1>1",
  "Chronicles1>2",
  "Chronicles1>3",
  "Chronicles1>4",
  "Chronicles1>5",
  "Chronicles1>6",
  "Chronicles1>7",
  "Chronicles1>8",
  "Chronicles1>9",
  "Chronicles1>10",
  "Chronicles1>11",
  "Chronicles1>12",
  "Chronicles1>13",
  "Chronicles1>14",
  "Chronicles1>15",
  "Chronicles1>16",
  "Chronicles1>17",
  "Chronicles1>18",
  "Chronicles1>19",
  "Chronicles1>20",
  "Chronicles1>21",
  "Chronicles1>22",
  "Chronicles1>23",
  "Chronicles1>24",
  "Chronicles1>25",
  "Chronicles1>26",
  "Chronicles1>27",
  "Chronicles1>28",
  "Chronicles1>29",
  "Chronicles2>1",
  "Chronicles2>2",
  "Chronicles2>3",
  "Chronicles2>4",
  "Chronicles2>5",
  "Chronicles2>6",
  "Chronicles2>7",
  "Chronicles2>8",
  "Chronicles2>9",
  "Chronicles2>10",
  "Chronicles2>11",
  "Chronicles2>12",
  "Chronicles2>13",
  "Chronicles2>14",
  "Chronicles2>15",
  "Chronicles2>16",
  "Chronicles2>17",
  "Chronicles2>18",
  "Chronicles2>19",
  "Chronicles2>20",
  "Chronicles2>21",
  "Chronicles2>22",
  "Chronicles2>23",
  "Chronicles2>24",
  "Chronicles2>25",
  "Chronicles2>26",
  "Chronicles2>27",
  "Chronicles2>28",
  "Chronicles2>29",
  "Chronicles2>30",
  "Chronicles2>31",
  "Chronicles2>32",
  "Chronicles2>33",
  "Chronicles2>34",
  "Chronicles2>35",
  "Chronicles2>36",
  "Ezra>1",
  "Ezra>2",
  "Ezra>3",
  "Ezra>4",
  "Ezra>5",
  "Ezra>6",
  "Ezra>7",
  "Ezra>8",
  "Ezra>9",
  "Ezra>10",
  "Nehemiah>1",
  "Nehemiah>2",
  "Nehemiah>3",
  "Nehemiah>4",
  "Nehemiah>5",
  "Nehemiah>6",
  "Nehemiah>7",
  "Nehemiah>8",
  "Nehemiah>9",
  "Nehemiah>10",
  "Nehemiah>11",
  "Nehemiah>12",
  "Nehemiah>13",
  "Esther>1",
  "Esther>2",
  "Esther>3",
  "Esther>4",
  "Esther>5",
  "Esther>6",
  "Esther>7",
  "Esther>8",
  "Esther>9",
  "Esther>10",
  "Job>1",
  "Job>2",
  "Job>3",
  "Job>4",
  "Job>5",
  "Job>6",
  "Job>7",
  "Job>8",
  "Job>9",
  "Job>10",
  "Job>11",
  "Job>12",
  "Job>13",
  "Job>14",
  "Job>15",
  "Job>16",
  "Job>17",
  "Job>18",
  "Job>19",
  "Job>20",
  "Job>21",
  "Job>22",
  "Job>23",
  "Job>24",
  "Job>25",
  "Job>26",
  "Job>27",
  "Job>28",
  "Job>29",
  "Job>30",
  "Job>31",
  "Job>32",
  "Job>33",
  "Job>34",
  "Job>35",
  "Job>36",
  "Job>37",
  "Job>38",
  "Job>39",
  "Job>40",
  "Job>41",
  "Job>42",
  "Psalms>1",
  "Psalms>2",
  "Psalms>3",
  "Psalms>4",
  "Psalms>5",
  "Psalms>6",
  "Psalms>7",
  "Psalms>8",
  "Psalms>9",
  "Psalms>10",
  "Psalms>11",
  "Psalms>12",
  "Psalms>13",
  "Psalms>14",
  "Psalms>15",
  "Psalms>16",
  "Psalms>17",
  "Psalms>18",
  "Psalms>19",
  "Psalms>20",
  "Psalms>21",
  "Psalms>22",
  "Psalms>23",
  "Psalms>24",
  "Psalms>25",
  "Psalms>26",
  "Psalms>27",
  "Psalms>28",
  "Psalms>29",
  "Psalms>30",
  "Psalms>31",
  "Psalms>32",
  "Psalms>33",
  "Psalms>34",
  "Psalms>35",
  "Psalms>36",
  "Psalms>37",
  "Psalms>38",
  "Psalms>39",
  "Psalms>40",
  "Psalms>41",
  "Psalms>42",
  "Psalms>43",
  "Psalms>44",
  "Psalms>45",
  "Psalms>46",
  "Psalms>47",
  "Psalms>48",
  "Psalms>49",
  "Psalms>50",
  "Psalms>51",
  "Psalms>52",
  "Psalms>53",
  "Psalms>54",
  "Psalms>55",
  "Psalms>56",
  "Psalms>57",
  "Psalms>58",
  "Psalms>59",
  "Psalms>60",
  "Psalms>61",
  "Psalms>62",
  "Psalms>63",
  "Psalms>64",
  "Psalms>65",
  "Psalms>66",
  "Psalms>67",
  "Psalms>68",
  "Psalms>69",
  "Psalms>70",
  "Psalms>71",
  "Psalms>72",
  "Psalms>73",
  "Psalms>74",
  "Psalms>75",
  "Psalms>76",
  "Psalms>77",
  "Psalms>78",
  "Psalms>79",
  "Psalms>80",
  "Psalms>81",
  "Psalms>82",
  "Psalms>83",
  "Psalms>84",
  "Psalms>85",
  "Psalms>86",
  "Psalms>87",
  "Psalms>88",
  "Psalms>89",
  "Psalms>90",
  "Psalms>91",
  "Psalms>92",
  "Psalms>93",
  "Psalms>94",
  "Psalms>95",
  "Psalms>96",
  "Psalms>97",
  "Psalms>98",
  "Psalms>99",
  "Psalms>100",
  "Psalms>101",
  "Psalms>102",
  "Psalms>103",
  "Psalms>104",
  "Psalms>105",
  "Psalms>106",
  "Psalms>107",
  "Psalms>108",
  "Psalms>109",
  "Psalms>110",
  "Psalms>111",
  "Psalms>112",
  "Psalms>113",
  "Psalms>114",
  "Psalms>115",
  "Psalms>116",
  "Psalms>117",
  "Psalms>118",
  "Psalms>119",
  "Psalms>120",
  "Psalms>121",
  "Psalms>122",
  "Psalms>123",
  "Psalms>124",
  "Psalms>125",
  "Psalms>126",
  "Psalms>127",
  "Psalms>128",
  "Psalms>129",
  "Psalms>130",
  "Psalms>131",
  "Psalms>132",
  "Psalms>133",
  "Psalms>134",
  "Psalms>135",
  "Psalms>136",
  "Psalms>137",
  "Psalms>138",
  "Psalms>139",
  "Psalms>140",
  "Psalms>141",
  "Psalms>142",
  "Psalms>143",
  "Psalms>144",
  "Psalms>145",
  "Psalms>146",
  "Psalms>147",
  "Psalms>148",
  "Psalms>149",
  "Psalms>150",
  "Proverbs>1",
  "Proverbs>2",
  "Proverbs>3",
  "Proverbs>4",
  "Proverbs>5",
  "Proverbs>6",
  "Proverbs>7",
  "Proverbs>8",
  "Proverbs>9",
  "Proverbs>10",
  "Proverbs>11",
  "Proverbs>12",
  "Proverbs>13",
  "Proverbs>14",
  "Proverbs>15",
  "Proverbs>16",
  "Proverbs>17",
  "Proverbs>18",
  "Proverbs>19",
  "Proverbs>20",
  "Proverbs>21",
  "Proverbs>22",
  "Proverbs>23",
  "Proverbs>24",
  "Proverbs>25",
  "Proverbs>26",
  "Proverbs>27",
  "Proverbs>28",
  "Proverbs>29",
  "Proverbs>30",
  "Proverbs>31",
  "Ecclesiastes>1",
  "Ecclesiastes>2",
  "Ecclesiastes>3",
  "Ecclesiastes>4",
  "Ecclesiastes>5",
  "Ecclesiastes>6",
  "Ecclesiastes>7",
  "Ecclesiastes>8",
  "Ecclesiastes>9",
  "Ecclesiastes>10",
  "Ecclesiastes>11",
  "Ecclesiastes>12",
  "SongofSolomon>1",
  "SongofSolomon>2",
  "SongofSolomon>3",
  "SongofSolomon>4",
  "SongofSolomon>5",
  "SongofSolomon>6",
  "SongofSolomon>7",
  "SongofSolomon>8",
  "Isaiah>1",
  "Isaiah>2",
  "Isaiah>3",
  "Isaiah>4",
  "Isaiah>5",
  "Isaiah>6",
  "Isaiah>7",
  "Isaiah>8",
  "Isaiah>9",
  "Isaiah>10",
  "Isaiah>11",
  "Isaiah>12",
  "Isaiah>13",
  "Isaiah>14",
  "Isaiah>15",
  "Isaiah>16",
  "Isaiah>17",
  "Isaiah>18",
  "Isaiah>19",
  "Isaiah>20",
  "Isaiah>21",
  "Isaiah>22",
  "Isaiah>23",
  "Isaiah>24",
  "Isaiah>25",
  "Isaiah>26",
  "Isaiah>27",
  "Isaiah>28",
  "Isaiah>29",
  "Isaiah>30",
  "Isaiah>31",
  "Isaiah>32",
  "Isaiah>33",
  "Isaiah>34",
  "Isaiah>35",
  "Isaiah>36",
  "Isaiah>37",
  "Isaiah>38",
  "Isaiah>39",
  "Isaiah>40",
  "Isaiah>41",
  "Isaiah>42",
  "Isaiah>43",
  "Isaiah>44",
  "Isaiah>45",
  "Isaiah>46",
  "Isaiah>47",
  "Isaiah>48",
  "Isaiah>49",
  "Isaiah>50",
  "Isaiah>51",
  "Isaiah>52",
  "Isaiah>53",
  "Isaiah>54",
  "Isaiah>55",
  "Isaiah>56",
  "Isaiah>57",
  "Isaiah>58",
  "Isaiah>59",
  "Isaiah>60",
  "Isaiah>61",
  "Isaiah>62",
  "Isaiah>63",
  "Isaiah>64",
  "Isaiah>65",
  "Isaiah>66",
  "Jeremiah>1",
  "Jeremiah>2",
  "Jeremiah>3",
  "Jeremiah>4",
  "Jeremiah>5",
  "Jeremiah>6",
  "Jeremiah>7",
  "Jeremiah>8",
  "Jeremiah>9",
  "Jeremiah>10",
  "Jeremiah>11",
  "Jeremiah>12",
  "Jeremiah>13",
  "Jeremiah>14",
  "Jeremiah>15",
  "Jeremiah>16",
  "Jeremiah>17",
  "Jeremiah>18",
  "Jeremiah>19",
  "Jeremiah>20",
  "Jeremiah>21",
  "Jeremiah>22",
  "Jeremiah>23",
  "Jeremiah>24",
  "Jeremiah>25",
  "Jeremiah>26",
  "Jeremiah>27",
  "Jeremiah>28",
  "Jeremiah>29",
  "Jeremiah>30",
  "Jeremiah>31",
  "Jeremiah>32",
  "Jeremiah>33",
  "Jeremiah>34",
  "Jeremiah>35",
  "Jeremiah>36",
  "Jeremiah>37",
  "Jeremiah>38",
  "Jeremiah>39",
  "Jeremiah>40",
  "Jeremiah>41",
  "Jeremiah>42",
  "Jeremiah>43",
  "Jeremiah>44",
  "Jeremiah>45",
  "Jeremiah>46",
  "Jeremiah>47",
  "Jeremiah>48",
  "Jeremiah>49",
  "Jeremiah>50",
  "Jeremiah>51",
  "Jeremiah>52",
  "Lamentations>1",
  "Lamentations>2",
  "Lamentations>3",
  "Lamentations>4",
  "Lamentations>5",
  "Ezekiel>1",
  "Ezekiel>2",
  "Ezekiel>3",
  "Ezekiel>4",
  "Ezekiel>5",
  "Ezekiel>6",
  "Ezekiel>7",
  "Ezekiel>8",
  "Ezekiel>9",
  "Ezekiel>10",
  "Ezekiel>11",
  "Ezekiel>12",
  "Ezekiel>13",
  "Ezekiel>14",
  "Ezekiel>15",
  "Ezekiel>16",
  "Ezekiel>17",
  "Ezekiel>18",
  "Ezekiel>19",
  "Ezekiel>20",
  "Ezekiel>21",
  "Ezekiel>22",
  "Ezekiel>23",
  "Ezekiel>24",
  "Ezekiel>25",
  "Ezekiel>26",
  "Ezekiel>27",
  "Ezekiel>28",
  "Ezekiel>29",
  "Ezekiel>30",
  "Ezekiel>31",
  "Ezekiel>32",
  "Ezekiel>33",
  "Ezekiel>34",
  "Ezekiel>35",
  "Ezekiel>36",
  "Ezekiel>37",
  "Ezekiel>38",
  "Ezekiel>39",
  "Ezekiel>40",
  "Ezekiel>41",
  "Ezekiel>42",
  "Ezekiel>43",
  "Ezekiel>44",
  "Ezekiel>45",
  "Ezekiel>46",
  "Ezekiel>47",
  "Ezekiel>48",
  "Daniel>1",
  "Daniel>2",
  "Daniel>3",
  "Daniel>4",
  "Daniel>5",
  "Daniel>6",
  "Daniel>7",
  "Daniel>8",
  "Daniel>9",
  "Daniel>10",
  "Daniel>11",
  "Daniel>12",
  "Hosea>1",
  "Hosea>2",
  "Hosea>3",
  "Hosea>4",
  "Hosea>5",
  "Hosea>6",
  "Hosea>7",
  "Hosea>8",
  "Hosea>9",
  "Hosea>10",
  "Hosea>11",
  "Hosea>12",
  "Hosea>13",
  "Hosea>14",
  "Joel>1",
  "Joel>2",
  "Joel>3",
  "Amos>1",
  "Amos>2",
  "Amos>3",
  "Amos>4",
  "Amos>5",
  "Amos>6",
  "Amos>7",
  "Amos>8",
  "Amos>9",
  "Obadiah>1",
  "Jonah>1",
  "Jonah>2",
  "Jonah>3",
  "Jonah>4",
  "Micah>1",
  "Micah>2",
  "Micah>3",
  "Micah>4",
  "Micah>5",
  "Micah>6",
  "Micah>7",
  "Nahum>1",
  "Nahum>2",
  "Nahum>3",
  "Habakkuk>1",
  "Habakkuk>2",
  "Habakkuk>3",
  "Zephaniah>1",
  "Zephaniah>2",
  "Zephaniah>3",
  "Haggai>1",
  "Haggai>2",
  "Zechariah>1",
  "Zechariah>2",
  "Zechariah>3",
  "Zechariah>4",
  "Zechariah>5",
  "Zechariah>6",
  "Zechariah>7",
  "Zechariah>8",
  "Zechariah>9",
  "Zechariah>10",
  "Zechariah>11",
  "Zechariah>12",
  "Zechariah>13",
  "Zechariah>14",
  "Malachi>1",
  "Malachi>2",
  "Malachi>3",
  "Malachi>4",
  "Matthew>1",
  "Matthew>2",
  "Matthew>3",
  "Matthew>4",
  "Matthew>5",
  "Matthew>6",
  "Matthew>7",
  "Matthew>8",
  "Matthew>9",
  "Matthew>10",
  "Matthew>11",
  "Matthew>12",
  "Matthew>13",
  "Matthew>14",
  "Matthew>15",
  "Matthew>16",
  "Matthew>17",
  "Matthew>18",
  "Matthew>19",
  "Matthew>20",
  "Matthew>21",
  "Matthew>22",
  "Matthew>23",
  "Matthew>24",
  "Matthew>25",
  "Matthew>26",
  "Matthew>27",
  "Matthew>28",
  "Mark>1",
  "Mark>2",
  "Mark>3",
  "Mark>4",
  "Mark>5",
  "Mark>6",
  "Mark>7",
  "Mark>8",
  "Mark>9",
  "Mark>10",
  "Mark>11",
  "Mark>12",
  "Mark>13",
  "Mark>14",
  "Mark>15",
  "Mark>16",
  "Luke>1",
  "Luke>2",
  "Luke>3",
  "Luke>4",
  "Luke>5",
  "Luke>6",
  "Luke>7",
  "Luke>8",
  "Luke>9",
  "Luke>10",
  "Luke>11",
  "Luke>12",
  "Luke>13",
  "Luke>14",
  "Luke>15",
  "Luke>16",
  "Luke>17",
  "Luke>18",
  "Luke>19",
  "Luke>20",
  "Luke>21",
  "Luke>22",
  "Luke>23",
  "Luke>24",
  "John>1",
  "John>2",
  "John>3",
  "John>4",
  "John>5",
  "John>6",
  "John>7",
  "John>8",
  "John>9",
  "John>10",
  "John>11",
  "John>12",
  "John>13",
  "John>14",
  "John>15",
  "John>16",
  "John>17",
  "John>18",
  "John>19",
  "John>20",
  "John>21",
  "Acts>1",
  "Acts>2",
  "Acts>3",
  "Acts>4",
  "Acts>5",
  "Acts>6",
  "Acts>7",
  "Acts>8",
  "Acts>9",
  "Acts>10",
  "Acts>11",
  "Acts>12",
  "Acts>13",
  "Acts>14",
  "Acts>15",
  "Acts>16",
  "Acts>17",
  "Acts>18",
  "Acts>19",
  "Acts>20",
  "Acts>21",
  "Acts>22",
  "Acts>23",
  "Acts>24",
  "Acts>25",
  "Acts>26",
  "Acts>27",
  "Acts>28",
  "Romans>1",
  "Romans>2",
  "Romans>3",
  "Romans>4",
  "Romans>5",
  "Romans>6",
  "Romans>7",
  "Romans>8",
  "Romans>9",
  "Romans>10",
  "Romans>11",
  "Romans>12",
  "Romans>13",
  "Romans>14",
  "Romans>15",
  "Romans>16",
  "Corinthians1>1",
  "Corinthians1>2",
  "Corinthians1>3",
  "Corinthians1>4",
  "Corinthians1>5",
  "Corinthians1>6",
  "Corinthians1>7",
  "Corinthians1>8",
  "Corinthians1>9",
  "Corinthians1>10",
  "Corinthians1>11",
  "Corinthians1>12",
  "Corinthians1>13",
  "Corinthians1>14",
  "Corinthians1>15",
  "Corinthians1>16",
  "Corinthians2>1",
  "Corinthians2>2",
  "Corinthians2>3",
  "Corinthians2>4",
  "Corinthians2>5",
  "Corinthians2>6",
  "Corinthians2>7",
  "Corinthians2>8",
  "Corinthians2>9",
  "Corinthians2>10",
  "Corinthians2>11",
  "Corinthians2>12",
  "Corinthians2>13",
  "Galatians>1",
  "Galatians>2",
  "Galatians>3",
  "Galatians>4",
  "Galatians>5",
  "Galatians>6",
  "Ephesians>1",
  "Ephesians>2",
  "Ephesians>3",
  "Ephesians>4",
  "Ephesians>5",
  "Ephesians>6",
  "Philippians>1",
  "Philippians>2",
  "Philippians>3",
  "Philippians>4",
  "Colossians>1",
  "Colossians>2",
  "Colossians>3",
  "Colossians>4",
  "Thessalonians1>1",
  "Thessalonians1>2",
  "Thessalonians1>3",
  "Thessalonians1>4",
  "Thessalonians1>5",
  "Thessalonians2>1",
  "Thessalonians2>2",
  "Thessalonians2>3",
  "Timothy1>1",
  "Timothy1>2",
  "Timothy1>3",
  "Timothy1>4",
  "Timothy1>5",
  "Timothy1>6",
  "Timothy2>1",
  "Timothy2>2",
  "Timothy2>3",
  "Timothy2>4",
  "Titus>1",
  "Titus>2",
  "Titus>3",
  "Philemon>1",
  "Hebrews>1",
  "Hebrews>2",
  "Hebrews>3",
  "Hebrews>4",
  "Hebrews>5",
  "Hebrews>6",
  "Hebrews>7",
  "Hebrews>8",
  "Hebrews>9",
  "Hebrews>10",
  "Hebrews>11",
  "Hebrews>12",
  "Hebrews>13",
  "James>1",
  "James>2",
  "James>3",
  "James>4",
  "James>5",
  "Peter1>1",
  "Peter1>2",
  "Peter1>3",
  "Peter1>4",
  "Peter1>5",
  "Peter2>1",
  "Peter2>2",
  "Peter2>3",
  "John1>1",
  "John1>2",
  "John1>3",
  "John1>4",
  "John1>5",
  "John2>1",
  "John3>1",
  "Jude>1",
  "Revelation>1",
  "Revelation>2",
  "Revelation>3",
  "Revelation>4",
  "Revelation>5",
  "Revelation>6",
  "Revelation>7",
  "Revelation>8",
  "Revelation>9",
  "Revelation>10",
  "Revelation>11",
  "Revelation>12",
  "Revelation>13",
  "Revelation>14",
  "Revelation>15",
  "Revelation>16",
  "Revelation>17",
  "Revelation>18",
  "Revelation>19",
  "Revelation>20",
  "Revelation>21",
  "Revelation>22",
];
const indexedBooksObj = {
  Romans,
  Corinthians1,
  Corinthians2,
  Galatians,
  Ephesians,
  Philippians,
  Colossians,
  Thessalonians1,
  Thessalonians2,
  Timothy1,
  Timothy2,
  Titus,
  Philemon,
  Hebrews,
  James,
  Peter1,
  Peter2,
  John1,
  John2,
  John3,
  Jude,
  Revelation,
};
const booksLocalStordArray = [
  "Genesis",
  "Exodus",
  "Leviticus",
  "Numbers",
  "Deuteronomy",
  "Joshua",
  "Judges",
  "Ruth",
  "Samuel1",
  "Samuel2",
  "Kings1",
  "Kings2",
  "Chronicles1",
  "Chronicles2",
  "Ezra",
  "Nehemiah",
  "Esther",
  "Job",
  "Psalms",
  "Proverbs",
  "Ecclesiastes",
  "SongofSolomon",
  "Isaiah",
  "Jeremiah",
  "Lamentations",
  "Ezekiel",
  "Daniel",
  "Hosea",
  "Joel",
  "Amos",
  "Obadiah",
  "Jonah",
  "Micah",
  "Nahum",
  "Habakkuk",
  "Zephaniah",
  "Haggai",
  "Zechariah",
  "Malachi",
  "Matthew",
  "Mark",
  "Luke",
  "John",
  "Acts",
];
const bookIndices = {
  Genesis: 1,
  Exodus: 2,
  Leviticus: 3,
  Numbers: 4,
  Deuteronomy: 5,
  Joshua: 6,
  Judges: 7,
  Ruth: 8,
  Samuel1: 9,
  Samuel2: 10,
  Kings1: 11,
  Kings2: 12,
  Chronicles1: 13,
  Chronicles2: 14,
  Ezra: 15,
  Nehemiah: 16,
  Esther: 17,
  Job: 18,
  Psalms: 19,
  Proverbs: 20,
  Ecclesiastes: 21,
  SongofSolomon: 22,
  Isaiah: 23,
  Jeremiah: 24,
  Lamentations: 25,
  Ezekiel: 26,
  Daniel: 27,
  Hosea: 28,
  Joel: 29,
  Amos: 30,
  Obadiah: 31,
  Jonah: 32,
  Micah: 33,
  Nahum: 34,
  Habakkuk: 35,
  Zephaniah: 36,
  Haggai: 37,
  Zechariah: 38,
  Malachi: 39,
  Matthew: 40,
  Mark: 41,
  Luke: 42,
  John: 43,
  Acts: 44,
  Romans: 45,
  Corinthians1: 46,
  Corinthians2: 47,
  Galatians: 48,
  Ephesians: 49,
  Philippians: 50,
  Colossians: 51,
  Thessalonians1: 52,
  Thessalonians2: 53,
  Timothy1: 54,
  Timothy2: 55,
  Titus: 56,
  Philemon: 57,
  Hebrews: 58,
  James: 59,
  Peter1: 60,
  Peter2: 61,
  John1: 62,
  John2: 63,
  John3: 64,
  Jude: 65,
  Revelation: 66,
};
const bookIndicesEnglish = {
  Genesis: "GEN",
  Exodus: "EXO",
  Leviticus: "LEV",
  Numbers: "NUM",
  Deuteronomy: "DEU",
  Joshua: "JOS",
  Judges: "JDG",
  Ruth: "RUT",
  Samuel1: "1SA",
  Samuel2: "2SA",
  Kings1: "1KI",
  Kings2: "2KI",
  Chronicles1: "1CH",
  Chronicles2: "2CH",
  Ezra: "EZR",
  Nehemiah: "NEH",
  Esther: "EST",
  Job: "JOB",
  Psalms: "PSA",
  Proverbs: "PRO",
  Ecclesiastes: "ECC",
  SongofSolomon: "SNG",
  Isaiah: "ISA",
  Jeremiah: "JER",
  Lamentations: "LAM",
  Ezekiel: "EZK",
  Daniel: "DAN",
  Hosea: "HOS",
  Joel: "JOL",
  Amos: "AMO",
  Obadiah: "OBA",
  Jonah: "JON",
  Micah: "MIC",
  Nahum: "NAM",
  Habakkuk: "HAB",
  Zephaniah: "ZEP",
  Haggai: "HAG",
  Zechariah: "ZEC",
  Malachi: "MAL",
  Matthew: "MAT",
  Mark: "MRK",
  Luke: "LUK",
  John: "JHN",
  Acts: "ACT",
  Romans: "ROM",
  Corinthians1: "1CO",
  Corinthians2: "2CO",
  Galatians: "GAL",
  Ephesians: "EPH",
  Philippians: "PHP",
  Colossians: "COL",
  Thessalonians1: "1TH",
  Thessalonians2: "2TH",
  Timothy1: "1TI",
  Timothy2: "2TI",
  Titus: "TIT",
  Philemon: "PHM",
  Hebrews: "HEB",
  James: "JAS",
  Peter1: "1PE",
  Peter2: "2PE",
  John1: "1JN",
  John2: "2JN",
  John3: "3JN",
  Jude: "JUD",
  Revelation: "REV",
};
const getBookScriptIntoLocalStor = function (_book) {
  const bookScript = document.createElement("script");
  bookScript.src = `https://cdn.githubraw.com/Web3Engineer/Bible-kjv/690c73fd/${_book}.js`;
  bookScript.async = false;
  bookScript.onload = function () {
    const book = eval(_book);
    localStorage.setItem(_book, JSON.stringify(book));
  };
  document.body.append(bookScript);
};

/*check to see if localstor books are availible, if not then load*/
(function () {
  for (let element of booksLocalStordArray) {
    if (localStorage.getItem(element) === null) {
      getBookScriptIntoLocalStor(element);
    }
  }
  /*check to see progress*/
  localStorage.getItem("proggress") === null && localStorage.setItem("proggress", 0);
})();

/*Waits a few seconds for localStor updates/checks, then jmnps into sync functionality */
window.onload = function () {
  /*display DOM elements/nodes*/
  (function () {
    /*Creating the output-text div*/ const outputText = document.createElement("div");
    outputText.classList.add("output-text");
    outputText.id = "output-text";
    document.body.appendChild(outputText);

    /*creating the dash-container-top div and its child elements*/
    const dashContainerTop = document.createElement("div");
    dashContainerTop.id = "dash-container-top";
    document.body.appendChild(dashContainerTop);

    /*creating dash-item divs and adding them to dashContainerTop*/
    const modeItem = document.createElement("div");
    modeItem.classList.add("dash-item");
    modeItem.id = "mode";
    modeItem.textContent = "⚫ / ☀️";
    dashContainerTop.appendChild(modeItem);

    const audioItem = document.createElement("div");
    audioItem.classList.add("dash-item");
    audioItem.id = "audioButton";
    audioItem.textContent = "🔊";
    dashContainerTop.appendChild(audioItem);

    const audioOffItem = document.createElement("div");
    audioOffItem.classList.add("dash-item");
    audioOffItem.id = "audioOff";
    audioOffItem.textContent = "🔇";
    dashContainerTop.appendChild(audioOffItem);

    const strongsItem = document.createElement("div");
    strongsItem.classList.add("dash-item");
    strongsItem.id = "strongs";
    strongsItem.textContent = "🔎📗";
    dashContainerTop.appendChild(strongsItem);

    const petsItem = document.createElement("div");
    petsItem.classList.add("dash-item");
    petsItem.id = "pets";
    petsItem.innerHTML = "🐠🌴"; /*petsItem.innerHTML = "🐠🌴<span class='hover-message'>floating message!</span>";*/
    dashContainerTop.appendChild(petsItem);

    const optionsItem = document.createElement("div");
    optionsItem.classList.add("dash-item");
    optionsItem.id = "options";
    optionsItem.textContent = "⚙️ / 🌏";
    dashContainerTop.appendChild(optionsItem);

    /*creating the button-leftArrow and button-rightArrow images*/
    const buttonLeftArrow = document.createElement("div");
    buttonLeftArrow.classList.add("no-select");
    buttonLeftArrow.id = "button-leftArrow";
    buttonLeftArrow.textContent = "⏪";
    document.body.appendChild(buttonLeftArrow);

    const buttonRightArrow = document.createElement("div");
    buttonRightArrow.classList.add("no-select");
    buttonRightArrow.id = "button-rightArrow";
    buttonRightArrow.textContent = "⏩";
    document.body.appendChild(buttonRightArrow);
  })();

  document.getElementById("loader").remove();

  /*compile>render assembled localStor data*/
  const renderAssembledlocalStor = function () {
    /* fetch and assemble current state for proccessing*/
    let proggressIndex = localStorage.getItem("proggress");
    let currentBookName = chapterArray[proggressIndex].split(">")[0].trim();
    let currentBookChapterInt = parseInt(chapterArray[proggressIndex].split(">")[1].trim()) - 1;
    let fullChapterString = "";

    if (booksLocalStordArray.includes(currentBookName)) {
      fullChapterString = `${currentBookName.toUpperCase()}📖CH.${currentBookChapterInt + 1}` + "\n";
      const fullBookChapter = JSON.parse(localStorage.getItem(currentBookName)).chapters[currentBookChapterInt].verses;
      for (let element of fullBookChapter) {
        fullChapterString += element.text + "\n";
      }
    } else {
      fullChapterString = `${currentBookName.toUpperCase()}📖CH.${currentBookChapterInt + 1}` + "\n";
      const fullBookChapter = indexedBooksObj[currentBookName].chapters[currentBookChapterInt].verses;
      for (let element of fullBookChapter) {
        fullChapterString += element.text + "\n";
      }
    }
    document.getElementById("output-text").innerText = fullChapterString;
  };
  renderAssembledlocalStor();

  /*setup listeners: arrow-button, dark/light mode, audio books*/
  const turnPageBackward = function () {
    isAutoScrolling = false;
    setTimeout(function () {
      window.scroll({
        top: 0,
        left: 0,
        behavior: "smooth",
      });
    }, 100);
    setTimeout(function () {
      if (parseInt(localStorage.getItem("proggress")) > 0) {
        localStorage.setItem("proggress", parseInt(localStorage.getItem("proggress")) - 1);
        renderAssembledlocalStor();
      }
    }, 200);
  };
  const turnPageForward = function () {
    isAutoScrolling = false;
    setTimeout(function () {
      window.scroll({
        top: 0,
        left: 0,
        behavior: "smooth",
      });
    }, 100);
    setTimeout(function () {
      if (parseInt(localStorage.getItem("proggress")) < 1188) {
        localStorage.setItem("proggress", parseInt(localStorage.getItem("proggress")) + 1);
        renderAssembledlocalStor();
      }
    }, 200);
  };

  document.getElementById("button-leftArrow").onclick = turnPageBackward;
  document.getElementById("button-rightArrow").onclick = turnPageForward;

  document.getElementById("mode").onclick = function () {
    document.body.classList.toggle("light-body");
    document.getElementById("output-text").classList.toggle("output-text-light");
  };

  let languageSelection = localStorage.getItem("langSelection") === null ? "filipino" : localStorage.getItem("langSelection");

  let audioActive = false;

  document.getElementById("audioButton").onclick = function () {
    const container = document.createElement("div");
    container.classList.add("grid-container-3-1fr");
    container.id = "container-audio";

    const gridItem1 = document.createElement("div");
    gridItem1.id = "play-audio";
    gridItem1.classList.add("grid-item-3-1fr");
    gridItem1.textContent = "🗣️";
    gridItem1.onclick = function () {
      if (audioActive !== true) {
        document.getElementById("play-audio").classList.add("no-select-no-event");
        audioActive = true;
        container.style.display = "none";
        document.getElementById("loader2").remove();

        if (languageSelection == "filipino") {
          const audioElement = document.createElement("audio");
          audioElement.id = "audio-element";
          document.body.append(audioElement);
          let proggress = parseInt(localStorage.getItem("proggress"));
          const bookName = chapterArray[proggress].split(">")[0].trim();
          const chapterNumber = parseInt(chapterArray[proggress].split(">")[1].trim());
          audioElement.src = `https://wordfree.org/bibles/app/audio/46/${bookIndices[bookName]}/${chapterNumber}.mp3`;
          /*onended, onloadeddata, oncanplay, oncanplaythrough, to listen for audio-related events.*/
          audioElement.oncanplay = function () {
            audioElement.play();
          };
          audioElement.onended = function () {
            turnPageForward();
            let proggress = parseInt(localStorage.getItem("proggress"));
            proggress++;
            const nextBook = chapterArray[proggress].split(">")[0].trim();
            const nextChapterNumber = parseInt(chapterArray[proggress].split(">")[1].trim());
            audioElement.src = `https://wordfree.org/bibles/app/audio/46/${bookIndices[nextBook]}/${nextChapterNumber}.mp3`;
            audioElement.oncanplay = function () {
              audioElement.play();
            };
          };
        }
        if (languageSelection == "english") {
          {
            const audioElement = document.createElement("audio");
            audioElement.id = "audio-element";
            document.body.append(audioElement);
            let proggress = parseInt(localStorage.getItem("proggress"));
            const bookName = chapterArray[proggress].split(">")[0].trim();
            const chapterNumber = parseInt(chapterArray[proggress].split(">")[1].trim());
            const filterBooksFunc = function () {
              if (chapterNumber.toString().length == 1) {
                return `https://publicdomainaudiobibles.com/content/mp3/KJV/${bookIndicesEnglish[bookName]}0${chapterNumber}.mp3`;
              }
              if (chapterNumber.toString().length >= 2) {
                return `https://publicdomainaudiobibles.com/content/mp3/KJV/${bookIndicesEnglish[bookName]}${chapterNumber}.mp3`;
              }
            };
            audioElement.src = filterBooksFunc();
            audioElement.oncanplay = function () {
              audioElement.play();
            };
            audioElement.onended = function () {
              turnPageForward();
              let proggress = parseInt(localStorage.getItem("proggress"));
              proggress++;
              const bookName = chapterArray[proggress].split(">")[0].trim();
              const chapterNumber = parseInt(chapterArray[proggress].split(">")[1].trim());
              const filterBooksFunc = function () {
                if (chapterNumber.toString().length == 1) {
                  return `https://publicdomainaudiobibles.com/content/mp3/KJV/${bookIndicesEnglish[bookName]}0${chapterNumber}.mp3`;
                }
                if (chapterNumber.toString().length >= 2) {
                  return `https://publicdomainaudiobibles.com/content/mp3/KJV/${bookIndicesEnglish[bookName]}${chapterNumber}.mp3`;
                }
              };
              audioElement.src = filterBooksFunc();
              audioElement.oncanplay = function () {
                audioElement.play();
              };
            };
          }
        }
      }
    };

    const gridItem2 = document.createElement("div");
    gridItem2.classList.add("grid-item-3-1fr");
    gridItem2.textContent = "⏸️";
    gridItem2.onclick = function () {
      document.getElementById("audio-element").pause();
      container.style.display = "none";
      document.getElementById("loader2").remove();
    };

    const gridItem3 = document.createElement("div");
    gridItem3.classList.add("grid-item-3-1fr");
    gridItem3.textContent = "▶️";
    gridItem3.onclick = function () {
      document.getElementById("audio-element").play();
      container.style.display = "none";
      document.getElementById("loader2").remove();
    };

    container.append(gridItem1, gridItem2, gridItem3);
    document.body.append(container);

    const loader2 = document.createElement("div");
    loader2.id = "loader2";
    loader2.style.cssText = `
        z-index: -1;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-size: cover;
        background-position: center;
        background-image: url('https://cdn.jsdelivr.net/gh/Web3Engineer/Bible-Web-App@main/handblueflame.gif');
    `;
    document.body.append(loader2);
  };

  document.getElementById("audioOff").onclick = function () {
    location.reload();
  };

  document.getElementById("pets").onclick = function () {
    alert(`🐄 🇸 🇨 🇷 🇮 🇵 🇹 🇺 🇷 🇪   🇨 🇷 🇮 🇹 🇹 🇪 🇷 🇸 🐓 

                            🅲 🅾 🅼 🅸 🅽 🅶  🆂 🅾 🅾 🅽

              𝙀𝙖𝙧𝙣  𝙇𝙞𝙫𝙚  𝘿𝙞𝙜𝙞𝙩𝙖𝙡  𝙋𝙚𝙩𝙨  
              𝙖𝙨  𝙔𝙤𝙪  𝙍𝙚𝙖𝙙  𝙎𝙘𝙧𝙞𝙥𝙩𝙪𝙧𝙚!

              love you Jake!`);
  };

  document.getElementById("strongs").onclick = function () {
    alert(`🅲 🅾 🅼 🅸 🅽 🅶  🆂 🅾 🅾 🅽  

        Strongs Concordance Helper! 

        Explore The Word deeper!`);
  };

  document.getElementById("options").onclick = function () {
    const container = document.createElement("div");
    container.classList.add("grid-container-2-1fr");
    container.id = "container";

    const gridItem1 = document.createElement("div");
    gridItem1.classList.add("grid-item-2-1fr");
    gridItem1.textContent = "🇺🇸";
    gridItem1.onclick = function () {
      localStorage.setItem("langSelection", "english");
      location.reload();
    };

    const gridItem2 = document.createElement("div");
    gridItem2.classList.add("grid-item-2-1fr");
    gridItem2.textContent = "🇵🇭";
    gridItem2.onclick = function () {
      localStorage.setItem("langSelection", "filipino");
      location.reload();
    };

    const gridItem3 = document.createElement("div");
    gridItem3.classList.add("grid-item-2-1fr");
    gridItem3.textContent = "🇲🇽";
    gridItem3.onclick = function () {
      alert("🇲🇽 Spanish language Soon! Prepare for the invasion, FJB!");
      location.reload();
    };

    const gridItem4 = document.createElement("div");
    gridItem4.classList.add("grid-item-2-1fr");
    gridItem4.textContent = "🇨🇳";
    gridItem4.onclick = function () {
      alert("🇨🇳 Mandarin/Chinese Language Soon! You will own nothing, and be happy!");
      location.reload();
    };

    container.append(gridItem1, gridItem2, gridItem3, gridItem4);
    document.body.append(container);
  };

  /**/
  /**/
  /**/
};
